# Generated by Django 5.1.7 on 2025-03-21 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mockapp', '0002_user_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Login',
        ),
    ]
