# Generated by Django 5.1.7 on 2025-03-24 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mockapp', '0004_user_login'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
    ]
