# Generated by Django 5.1.7 on 2025-04-03 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockapp', '0005_rename_user_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='status',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='login',
            name='user_type',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Experts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('dob', models.DateField()),
                ('contact', models.CharField(max_length=15)),
                ('Login', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mockapp.login')),
            ],
        ),
    ]
