# Generated by Django 5.1.7 on 2025-04-03 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mockapp', '0006_login_status_login_user_type_experts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experts',
            old_name='Login',
            new_name='Login_id',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='Login',
            new_name='Login_id',
        ),
    ]
