# Generated by Django 5.1.7 on 2025-04-09 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockapp', '0007_rename_login_experts_login_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experts',
            name='experience',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='experts',
            name='field',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
