# Generated by Django 5.1.7 on 2025-04-09 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockapp', '0008_experts_experience_experts_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experts',
            name='field',
            field=models.CharField(choices=[('Technology', 'Technology'), ('Finance', 'Finance'), ('Healthcare', 'Healthcare'), ('Marketing', 'Marketing')], default='Technology', max_length=100),
        ),
    ]
