# Generated by Django 5.1.7 on 2025-04-09 10:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockapp', '0009_alter_experts_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experts',
            name='field',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.CreateModel(
            name='InterviewTips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip', models.TextField()),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mockapp.login')),
            ],
        ),
    ]
