# Generated by Django 5.1.7 on 2025-04-15 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockapp', '0010_alter_experts_field_interviewtips'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewtips',
            name='expert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mockapp.experts'),
        ),
    ]
