# Generated by Django 5.1.7 on 2025-04-23 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mockapp', '0012_chat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chat',
        ),
    ]
