# Generated by Django 5.1.7 on 2025-04-24 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mockapp', '0014_chat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='rec_id',
            new_name='receiver_id',
        ),
        migrations.RenameField(
            model_name='chat',
            old_name='snd_id',
            new_name='sender_id',
        ),
    ]
