# Generated by Django 5.1.7 on 2025-05-04 14:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockapp', '0015_rename_rec_id_chat_receiver_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('user', 'User'), ('expert', 'Expert')], max_length=10)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mockapp.experts')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mockapp.users')),
            ],
        ),
        migrations.DeleteModel(
            name='chat',
        ),
    ]
