# Generated by Django 5.1.5 on 2025-07-04 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockapp', '0017_chat_delete_chatmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='MockScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_category', models.CharField(max_length=100)),
                ('question_text', models.TextField()),
                ('speech_confidence', models.FloatField()),
                ('facial_confidence', models.FloatField()),
                ('combined_confidence', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mockapp.login')),
            ],
        ),
    ]
